- name: Play-01
  hosts: web
  tasks:
  - name: Play-01 task-01
    ansible.builtin.debug:
      msg: "hi falsh man"

- name: Play-02
  hosts: web
  tasks:
  - name: Play-02
    ansible.builtin.debug:
    msg: "good morning"