- name: variables
  hosts: web
  vars:
    course: "aws devops"
    trainer: "SivaKumarReddy"
  tasks:
  - name: print info
    ansible.builtin.debug:
      msg: "I am learning {{course}}, trainer: {{trainer}}"