- name: check number is less than 10 or not
  hosts: local
  connection: local
  vars_prompt:
  - name: my_number
    prompt: enter number
    private: false
  tasks:
    - name: print this if less than 10
      ansible.builtin.debug:
        msg: "number is {{ my_number }} is less than 10"
      when: my_number | int < 10

    - name: print this if greater than 10
      ansible.builtin.debug:
        msg: "number is {{ my_number }} is greater than 10"
      when: my_number | int >= 10