- name: loops
  hosts: web
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "hello {{ item }}"
    loop:
    - aditya
    - adithya
    - aditya reddy
    - adithya reddy